## QUESTIONS

Implement the Question using scikit learn library. Plot the given samples Bad in Red color
and Good in green color. Also plot the decision boundary. Calculate the distance using Euclidean, Manhattan,
and Minkowski and compare.

In [36]:
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd

data = pd.read_csv("data.csv")
X = data.iloc[:,:2]
y = data.iloc[:,2:]
y = np.array(y)
def convert(x):
    if x=='Good':
        return 1
    return 0
y = list(map(convert,y))
data["Classification"] = y

#Using Minkowski
neigh = KNeighborsClassifier(n_neighbors=3,p=3, metric='minkowski')
neigh.fit(X,y)

print("Good" if neigh.predict([[3,7]]) else "Bad")

#Using Eucildean
neigh = KNeighborsClassifier(n_neighbors=3,p=2, metric='euclidean')
neigh.fit(X,y)

print("Good" if neigh.predict([[3,7]]) else "Bad")

#Using Manhattan Distance
neigh = KNeighborsClassifier(n_neighbors=3,p=1, metric='manhattan')
neigh.fit(X,y)

print("Good" if neigh.predict([[3,7]]) else "Bad")

Bad
Bad
Good

In [37]:
import pandas as pd
import numpy as np

def euclidean(x1,y1,x,y):
    return ((x1-x)**2 + (y1-y)**2)**(1/2)

def manhattan(x1,y1,x,y):
    return abs(x1-x) + abs(y1-y)

def minkowski(x1,y1,x,y,p):
    return ((abs(x1-x))**p + (abs(y1-y))**p)**(1/p)

data = pd.read_csv("data.csv")

c1x,c1y,c2x,c2y = 7,7,3,4 
data["Distance c1"] = [0]*len(data)
data["Distance c2"] = [0]*len(data)

#Using Eucildean
clusters = []
flag = False
while(flag == False):
    for i in range(len(data)):
       # data.iloc[i:i+1,3:4] = euclidian(data.iloc[i:i+1,0:1],data.iloc[i:i+1,1:2],c1x,c1y)
        data.iloc[i:i+1,4:] = euclidian(data.iloc[i:i+1,0:1],data.iloc[i:i+1,0:1],c2x,c2y)
    break
    
data

   Acid Durability  Strength Classification  Distance c1  Distance c2
0                7         7            Bad            0     5.000000
1                7         4            Bad            0     5.000000
2                3         4           Good            0     1.000000
3                1         4           Good            0     3.605551
4                4         5            Bad            0     1.000000
5                3         5           Good            0     1.000000
6                4         6            Bad            0     1.000000
7                8         7            Bad            0     6.403124
8                7         9           Good            0     5.000000
9                8         8            Bad            0     6.403124